### ISSUE TITLE
1000HP模式和攻击吸血模式触发后插件失效

### ISSUE THREAD

**Issue by YunQi7777** [TitaniumLithium/CS2FunMatchPlugin#3]
在以git上的cs2-modded-server为基础添加插件的windows端服务器上运行插件时
此时其他模式插件已禁用，启用的通用插件如图
![屏幕截图 2024-06-15 221957](https://github.com/TitaniumLithium/CS2FunMatchPlugin/assets/172915650/15cba6e8-4ea5-4590-be72-ea93241df403)
触发其他模式时均正常，但在服务器上触发1000HP模式后只有1人1000HP，触发吸血模式后无效，且触发这两种后插件都失效需要重启生效
失效时服务器窗口反馈如图
![屏幕截图 2024-06-15 220758](https://github.com/TitaniumLithium/CS2FunMatchPlugin/assets/172915650/2b7f1e10-d76f-4793-8dea-29906a8fd4a8)
请问一下是什么原因造成的
顺带问一下funlists等命令是在什么地方输入触发，我在游戏内控制台与聊天框和服务器控制台输入均无反馈，不知道是不是还是插件冲突

**Comment by YunQi7777** [comment]
补充：1000HP模式和吸血模式确认是插件冲突，在卸载一部分插件后成功生效
但funlists仍不知道怎么使用，求解答

**Comment by YunQi7777** [comment]
二补：重启了一次服务器后卸载插件也不一定生效，原因未知
附新的服务器反馈
![屏幕截图 2024-06-15 231532](https://github.com/TitaniumLithium/CS2FunMatchPlugin/assets/172915650/67ddc9fc-905c-4b10-8142-c2a36856f3ad)

**Comment by TitaniumLithium** [comment]
- `fun_lists`为控制台指令 在客户端或者服务端输入均可
    其他指令如`!fun_random`同样为控制台指令 但需要@css/root权限

- 1000HP和吸血模式中：将在回合开始时遍历每个玩家设置最大生命值和当前生命值 （吸血还会额外注册”玩家受伤“事件）
   

> 服务器上触发1000HP模式后只有1人1000HP

结合报错（大概意思是 一个值为null的未赋值对象 去访问了它的成员）
说明在遍历玩家时 获取的玩家中（ccsplayercontroler）存在无效的
然后直接抛出异常 后面的就没有执行

按理说这应该不会和其他插件冲突。有其他插件也在回合开局获取了玩家 或者修改了玩家血量的么？冲突的插件是什么插件？

- CounterStrikeSharp版本？如果CounterStrikeSharp版本为[v224](https://github.com/roflmuffin/CounterStrikeSharp/releases/tag/v224)以及以下的话 期望会报错 因为在这之前不会检查player的有效性
[cs#v224更新详情](https://github.com/roflmuffin/CounterStrikeSharp/pull/417#issue-2242089878)
目前我build使用的版本为239 最新版本242

**Comment by TitaniumLithium** [comment]
才发现readme文件这个指令少打了个下划线2333 已修改

**Comment by YunQi7777** [comment]
CSS用的是V242，冲突服务器插件没搞清楚，之前重启服务器后unload了所有的插件仍然存在bug，复现不出来之前1000血量模式生效的情况，是否有可能是服务器开启了tv_enable 1导致存在一个隐藏玩家使得调用失效

**Comment by TitaniumLithium** [comment]
[FunMatchPlugin_branch_issue#3.zip](https://github.com/user-attachments/files/15855887/FunMatchPlugin_branch_issue.3.zip)
手动检查了player的有效性 请下载替换后查看问题是否仍然存在

您可以通过`status`指令在游戏内查看当前所有玩家

**Comment by YunQi7777** [comment]
通过status查看发现存在名称为空的玩家
但并不影响插件使用，在踢出sourceTV玩家后插件可正常使用
![屏幕截图 2024-06-16 132745](https://github.com/TitaniumLithium/CS2FunMatchPlugin/assets/172915650/f1b10cc4-5762-470f-8d3d-5ec8e1fcf3ea)
附可能是开局获取玩家信息的插件，但似乎并未冲突
![屏幕截图 2024-06-16 133718](https://github.com/TitaniumLithium/CS2FunMatchPlugin/assets/172915650/fd8add7c-bd28-4c99-bf9b-deb9ea5380c8)

感觉可能是SourceTV为有效玩家但并不实际存在于游戏内造成的问题，踢出后可以稳定使用1000HP和吸血模式，已解决，感谢
